### ISSUE TITLE
Fatal error: Class 'Expose\FilterCollection' not found

### ISSUE THREAD

**Issue by nisser** [enygma/expose#61]
From the example...

Help?

**Comment by Awnage** [comment]
The example assumes a few pieces that we should be more explicit about. 

Create composer.json
```
{
  "require":{
    "enygma/expose":"2.*"
  }
} 
```
 Install the dependencies:
`php composer.phar install`

Then you need to start your php file with:
```
<?php
require 'vendor/autoload.php';
require 'vendor/enygma/expose/tests/MockLogger.php';
```

**Comment by Awnage** [comment]
I have updated the README to hopefully make this more clear.

**Comment by nisser** [comment]
Followed all steps, same.

I'm using it in public html and the stuff got installed outside of it. Problem?

**Comment by Awnage** [comment]
What errors are showing up in your web error logs?
Care to post your index.php in a pastebin?

**Comment by nisser** [comment]
Thanks for your reply. No index.php just using your example.php and still see
Fatal error: Class 'Expose\FilterCollection' not found 

Followed the steps, installed via composer etc...but the files are outside of public html and the example is in public html. Can it still "see" the autoloader?

**Comment by Awnage** [comment]
It looks like you are not correctly specifying your directory path. If your directory structure is like this:
```
composer.json
public\
public\index.php
vendor\
```
You need to 
```
<?php
require '../vendor/autoload.php';
```
